### ISSUE TITLE
iframe width breaks layout at mobile view

### ISSUE THREAD

**Issue by emindeniz99** [Compec/boundatacamp#6]
https://github.com/Compec/boundatacamp/blob/bdb745c1987c7377993485d8a48cae6b45faad1e/datathon/index.html#L225
width="100%" can be used instead of fixed value

![image](https://user-images.githubusercontent.com/44745432/99641337-2bca4980-2a5b-11eb-857b-ce667b495297.png)
![image](https://user-images.githubusercontent.com/44745432/99641358-34228480-2a5b-11eb-9841-e526f61a25fc.png)

**Comment by burkaykinik** [comment]
duzelttim simdi tesekkur ederim
